name: Mapcdk
version: '${project.version}'
main: me.maplef.mapcdk.Mapcdk
api-version: 1.13
commands:
  mapcdk:
    description: "main command for MapCDK"
    permission: "mapcdk"
permissions:
  mapcdk.*:
    description: "full access to MapCDK"
    children:
      mapcdk.help: true
      mapcdk.newcdk: true
      mapcdk.continue: true
      mapcdk.list: true
  mapcdk:
    default: true
  mapcdk.help:
    default: true
  mapcdk.newcdk:
    default: op
  mapcdk.continue:
    default: op
  mapcdk.list:
    default: op